shoutme/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
        path('', include('tellme.urls')),

]

tellme/urls.py
from django.urls import path
from tellme import views
from django.contrib.auth import views as auth_views

app_name = 'tellme'

urlpatterns = [
    path('',views.home,name="index"),
    path('login/',auth_views.login,{'template_name': 'form.html'},name='login'),
    path('logout/',auth_views.logout,{'template_name': 'home.html'}),
    path('signup/', views.signup,name="signup"),
    path("form/",views.test),
    path('profile/', views.profile,name="profileupdate"),
    path('viewshout/',views.viewshout,name='viewshout'),

    path("<username>/",views.propage,name="profile"),

]

tellme/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class Comments(models.Model):
    profile = models.ForeignKey(User,on_delete=models.CASCADE)
    comment = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return "{} - {}".format(self.profile,self.comment)


class info(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.TextField(max_length=300,default="No biography added yet")
    photo = models.URLField(verbose_name="Enter your photo URL", default='https://www.polyvore.com/cgi/img-thing?.out=jpg&size=l&tid=16560098')

    def __str__(self):
        return "Additional info of {}".format(self.user)

tellme/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from .models import Comments,info


class SignupForm(UserCreationForm):   
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'first_name', 'last_name',]
        #exclude = ["bio"]


class TestForm(forms.Form):
    ct = (('m', 'Male'), ('f', 'Female'))

    name = forms.CharField(min_length=3)
    age = forms.IntegerField(min_value=18)
    gender = forms.ChoiceField(choices=ct)
    photo = forms.FileField()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment']


class ProfileUpdate(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']

class ProfileUpdate2(forms.ModelForm):
    class Meta:
        model = info
        exclude = ["user"]

tellme/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404,HttpResponseRedirect
from .forms import SignupForm, TestForm,User,CommentForm,ProfileUpdate,ProfileUpdate2,info
from .models import Comments

# Create your views here.

def home(request):
    return render(request,"home.html")

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            u = form.save()
            info.objects.create(user=u)
            return HttpResponseRedirect('/login')
        return render(request,'r.html',{'form':form})
    return render(request,'r.html',{'form':SignupForm})


def test(request):
    if request.method == "POST":
        print(request.FILES)
        form  = TestForm(request.POST,request.FILES)
        if form.is_valid():
            return HttpResponse("success")
        return render(request,'form.html',{'form':form})
    return render(request,'form.html',{'form':TestForm})


def propage(request,username):
    pro = User.objects.get(username=username)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            com = form.save(commit=False)
            com.profile = pro
            com.save()
            return HttpResponseRedirect("/")
    return render(request,'profile.html',{'profile': pro, 'form':CommentForm})


def profile(request):
    if str(request.user) == "AnonymousUser":
        return HttpResponse("You are not logged in, Log In First to edit profile")
    if request.method == "POST":
        form = ProfileUpdate(request.POST,instance=request.user)
        form2 = ProfileUpdate2(request.POST,request.FILES,instance=request.user.info)
        if form.is_valid and form2.is_valid():
            print("!!!!!!!!  valid !!!!!!!!!!!!")
            form2.save()
            form.save()
            return HttpResponseRedirect("/profile")
    form = ProfileUpdate(instance=request.user)
    form2 = ProfileUpdate2(instance=request.user.info)
    return render(request,'profileupdate.html',{'form': form, "form2":form2})
    

def viewshout(request):
    if str(request.user) == 'AnonymousUser':
        return HttpResponseRedirect("/login")
    clist = Comments.objects.filter(profile=request.user)
    return render(request,'viewshout.html',{'clist':clist})

tellme/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
	<link rel="stylesheet" type="text/css" href="{% static 'beauter.min.css'%}"/>
	<link rel="shortcut icon" type="image/gif" href="https://cdn0.iconfinder.com/data/icons/avatars-and-smiles-collection/110/Icons__excellent_pupil-64.png"/>
</head>

<body class="_nightblue">
<!-- NAVBAR starts here -->
<ul class="topnav" id="myTopnav" style="">
     <li>
        <a class="brand" href="{% url "tellme:index" %}"><img src="http://beauter.outboxcraft.com/img/chry.svg" style="width:20px"> ShoutMe</a>
     </li>
     <li>
        <a href="{% url "tellme:profileupdate" %}">My Profile</a>
     </li>
     <li>
        <a href="javascript:void(0);" onclick="alert('In Beta Mode..!!')">Search</a>
     </li>
     <li class="-icon">
        <a href="javascript:void(0);" onclick="topnav('myTopnav')">☰</a>
     </li>
     <li class="" style="float:right; display:inline!important">
          {% if request.user.username == '' %}
         <a href="{% url 'tellme:login' %}"><b>Login Here</b></a>
         {% else %}
         <a href="{% url 'tellme:profile' request.user.username %}"><b>Hey {{ request.user}}</b></a>
         {% endif %}
     </li>
     
  </ul>
<!-- navbar ends here -->

{% block body %}{% endblock %} 



<!-- design your site here -->

<script src="https://rawgit.com/outboxcraft/beauter/master/beauter.min.js"></script>
</body>

</html>

tellme/templates/blog.html
{% for p in posts %}

<a href="{{ p.id }}">{{p.title}}</a>

{% endfor %}

tellme/templates/classview.html
{% for i in blogpost %}

{{ i.title }}

{% endfor %}

tellme/templates/form.html
{% include "base.html" %}

<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
            <h3>Sign In</h3>
            {{ form.as_p }}
            <input type="submit" value="Submit" class="_primary">
        
    </form>
</div>

tellme/templates/home.html
{% extends 'base.html' %}

{% block body %}

<div class="container _shadow">
    <div class="jumbo">
        <h1>This is <small>Shout</small>Me<br></h1>
        <h3>Hello {{ request.user }}!!</h3>
        {% if request.user.username == '' %}
        <a class="btn _primary _xlarge" href="/signup"><b>SignUp Here</b></a>
        {% else %}
        <form  action="/{{request.user}}" method='GET' ><input type='submit' class='_success _xlarge' value='Go to Your Page'></form>
        <h4><b>OR</b></h4>
        <form  action="{% url 'tellme:viewshout' %}" method='GET' ><input type='submit' class='_primary _xlarge' value='See What You Got'></form>
        {% endif %}
    </div>
</div>

{%endblock%}

tellme/templates/profile.html
<link href="https://fonts.googleapis.com/css?family=Sacramento" rel="stylesheet"> 
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="container">
    <div class="col m7">
        <div class="jumbo _nightblue">
            <h1>{{profile.first_name}} {{ profile.last_name}}</h1>
            <img class="-circle" style="width:210px" src="{{ profile.info.photo }}">
            <h2><small>ShoutMe/</small><b>{{ profile.username }}</b></h2>
            <h5><i>Last Checked {{ profile.last_login }}</i></h5>
            <p>{{ profile.email }}</p>
            <p class="" style="font-family:'Sacramento'; color:white; font-size:34px ">{{ profile.info.bio }}</p>
        </div>
    </div>

    <div class="col m5">
        <div class="jumbo -round _shadow">
            <h1><br>Tell Me Something</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <textarea name="comment" id="id_comment" cols="30" rows="55" style="height:100px;"></textarea>
                <button type="submit" class="_xlarge _primary _shadow">Shout ME</button>
            </form>
            
        </div>
    </div>
</div>
{% endblock %}

tellme/templates/profileupdate.html
{% extends 'base.html' %}

{% block body %}
<div class="container jumbo _shadow _alignLeft">
    <form enctype="multipart/form-data" action="" method="POST" class="off-2">
        {% csrf_token %}
        {{form.as_p}}
        {{form2.as_p}}
        <button type="submit" class=" _round _primary">Update Profile</button>
    </form>
</div>
{% endblock %}

tellme/templates/r.html
{%include 'base.html'%}
<div class="container">
    <h2>Sign up</h2>
    <form method="post">
      {% csrf_token %}
      <table>
      {{ form.as_p }}
      <td><input type="submit" value="Signup" class="_primary"></td>
      </table>  
    </form>
</div>


tellme/templates/shoe.html
{% for q in arr %}

{{q}} <br>
<ul>
{% for i in q.choice_set.filter %}
<li>
{{i}}
</li>
{% endfor %}
</ul>
{% endfor %}

tellme/templates/tellme/blogpost_detail.html
{{ blogpost.post }}

tellme/templates/viewshout.html
{% extends 'base.html' %}

{% block body %}

<div class='container jumbo _shadow'>
    

{% for c in clist %}

<h5><span class='_brown _shadow _round' style="padding:5px;">{{c.comment}}</span></h5>

{% endfor %}

</div>

{% endblock %}